INSERT INTO category(categoryname) VALUES ('Houses');
INSERT INTO category(categoryname) VALUES ('Cars');
INSERT INTO category(categoryname) VALUES ('Furnitures');

INSERT INTO shopuser(email, password, username, role) VALUES ('admin@admin.pl', 'admin', 'admin', 'ADMIN');
INSERT INTO shopuser(email, password, username, role) VALUES ('user@user.pl', 'user', 'user', 'USER');

INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House1', '5', '0Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House2', '10', '1Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House3', '15', '4Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House4', '20', '9Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House5', '25', '16Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House6', '30', '25Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House7', '35', '36Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House8', '40', '49Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House9', '45', '64Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House10', '50', '81Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House11', '55', '100Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House12', '60', '121Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House13', '65', '144Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House14', '70', '169Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House15', '75', '196Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House16', '80', '225Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House17', '85', '256Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House18', '90', '289Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House19', '95', '324Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House20', '100', '361Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House21', '105', '400Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House22', '110', '441Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House23', '115', '484Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House24', '120', '529Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House25', '125', '576Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House26', '130', '625Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House27', '135', '676Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House28', '140', '729Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House29', '145', '784Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House30', '150', '841Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House31', '155', '900Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House32', '160', '961Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House33', '165', '1024Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House34', '170', '1089Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House35', '175', '1156Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House36', '180', '1225Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House37', '185', '1296Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House38', '190', '1369Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House39', '195', '1444Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House40', '200', '1521Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House41', '205', '1600Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House42', '210', '1681Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House43', '215', '1764Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House44', '220', '1849Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House45', '225', '1936Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House46', '230', '2025Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House47', '235', '2116Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House48', '240', '2209Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House49', '245', '2304Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('House50', '250', '2401Housecode', 1);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car1', '255', '0Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car2', '260', '1Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car3', '265', '4Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car4', '270', '9Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car5', '275', '16Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car6', '280', '25Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car7', '285', '36Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car8', '290', '49Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car9', '295', '64Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car10', '300', '81Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car11', '305', '100Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car12', '310', '121Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car13', '315', '144Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car14', '320', '169Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car15', '325', '196Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car16', '330', '225Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car17', '335', '256Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car18', '340', '289Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car19', '345', '324Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car20', '350', '361Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car21', '355', '400Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car22', '360', '441Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car23', '365', '484Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car24', '370', '529Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car25', '375', '576Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car26', '380', '625Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car27', '385', '676Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car28', '390', '729Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car29', '395', '784Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car30', '400', '841Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car31', '405', '900Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car32', '410', '961Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car33', '415', '1024Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car34', '420', '1089Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car35', '425', '1156Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car36', '430', '1225Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car37', '435', '1296Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car38', '440', '1369Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car39', '445', '1444Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car40', '450', '1521Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car41', '455', '1600Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car42', '460', '1681Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car43', '465', '1764Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car44', '470', '1849Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car45', '475', '1936Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car46', '480', '2025Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car47', '485', '2116Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car48', '490', '2209Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car49', '495', '2304Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Car50', '500', '2401Carcode', 2);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture1', '505', '0Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture2', '510', '1Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture3', '515', '4Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture4', '520', '9Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture5', '525', '16Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture6', '530', '25Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture7', '535', '36Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture8', '540', '49Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture9', '545', '64Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture10', '550', '81Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture11', '555', '100Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture12', '560', '121Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture13', '565', '144Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture14', '570', '169Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture15', '575', '196Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture16', '580', '225Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture17', '585', '256Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture18', '590', '289Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture19', '595', '324Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture20', '600', '361Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture21', '605', '400Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture22', '610', '441Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture23', '615', '484Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture24', '620', '529Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture25', '625', '576Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture26', '630', '625Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture27', '635', '676Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture28', '640', '729Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture29', '645', '784Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture30', '650', '841Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture31', '655', '900Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture32', '660', '961Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture33', '665', '1024Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture34', '670', '1089Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture35', '675', '1156Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture36', '680', '1225Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture37', '685', '1296Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture38', '690', '1369Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture39', '695', '1444Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture40', '700', '1521Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture41', '705', '1600Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture42', '710', '1681Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture43', '715', '1764Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture44', '720', '1849Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture45', '725', '1936Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture46', '730', '2025Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture47', '735', '2116Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture48', '740', '2209Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture49', '745', '2304Furniturecode', 3);
INSERT INTO product(name, price, uniqueProductCode, categoryid) VALUES ('Furniture50', '750', '2401Furniturecode', 3);

--example orders
INSERT INTO orders(orderidentifier, userid) VALUES ('8d186661-d6be-41d4-9a59-860bc7cb6dbd', 2);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (5, 20.0, 1, 1);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (12, 26.0, 1, 2);

INSERT INTO orders(orderidentifier, userid) VALUES ('8d186661-d6be-41d4-9a59-860bc7cb6dbe', 2);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (4, 1.0, 2, 7);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (12, 26.0, 2, 17);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (1, 12.0, 2, 65);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (2, 18.5, 2, 134);

INSERT INTO orders(orderidentifier, userid) VALUES ('8d186661-d6be-41d4-9a59-860bc7cb6dbf', 1);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (8, 10.0, 3, 70);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (7, 15.0, 3, 80);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (1, 55.0, 3, 100);

INSERT INTO orders(orderidentifier, userid) VALUES ('8d186661-d6be-41d4-9a59-860bc7cb6dbg', 2);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (1, 50.0, 4, 12);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (1, 45.0, 4, 13);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (1, 55.0, 4, 14);

INSERT INTO orders(orderidentifier, userid) VALUES ('8d186661-d6be-41d4-9a59-860bc7cb6dbh', 2);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (1, 30.0, 5, 46);

INSERT INTO orders(orderidentifier, userid) VALUES ('8d186661-d6be-41d4-9a59-860bc7cb6dbi', 2);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (1, 20.0, 6, 66);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (1, 25.0, 6, 2);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (1, 35.0, 6, 34);

INSERT INTO orders(orderidentifier, userid) VALUES ('8d186661-d6be-41d4-9a59-860bc7cb6dbj', 1);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (2, 1.0, 7, 71);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (2, 2.0, 7, 82);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (3, 6.0, 7, 24);
INSERT INTO lineitem(productamount, productprice, orderid, product_productid) VALUES (3, 5.0, 7, 33);